defmodule SymphonyElixir.OrchestratorStatusTest do
  use SymphonyElixir.OrchestratorStatusTest.Sections.OrchestratorStatus1
  use SymphonyElixir.OrchestratorStatusTest.Sections.OrchestratorStatus2
  use SymphonyElixir.OrchestratorStatusTest.Sections.OrchestratorStatus3
  use SymphonyElixir.OrchestratorStatusTest.Sections.OrchestratorStatus4
end
