defmodule SymphonyElixir.OrchestratorStatusTest do
  use SymphonyElixir.TestSupport.LocalitySections.OrchestratorStatus1
  use SymphonyElixir.TestSupport.LocalitySections.OrchestratorStatus2
  use SymphonyElixir.TestSupport.LocalitySections.OrchestratorStatus3
  use SymphonyElixir.TestSupport.LocalitySections.OrchestratorStatus4
end
